server:
  port: 9000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://EUREKA-SERVER

spring:
  cloud:
    gateway:
      
      routes:
       - id: busService
         uri: lb://BUS-SERVICE
         predicates:
         - Path=/bus-api/** 
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
