server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://EUREKA-SERVER 
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri : http://${keycloakServerHost}:${keycloakServerPort}/realms/full-stack 
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
db:
  path: http://localhost:8983/solr/bus
