server:
  port: 9000

eureka:
  client:
    service-url:
      default-zone: http://localhost:EUREKA-SERVER

spring:
  cloud:
    gateway:
      routes:
       - id: excelService
         uri: lb://EXCEL-SERVICE
         predicates:
         - Path=/excel/** 
      
#        - id: scheduleService
#          uri: lb://SCHEDULE-SERVICE
#          predicates:
#          - Path=/schedule/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
