server:
  port: 8082
  
spring:
  application:
    name: EXCEL-SERVICE
  config:
    import: configserver:http://localhost:8888
      
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761

file:
  path: C:\\projectDemo\\Excelsheets\\DailySchedule.xlsx
